### ISSUE TITLE
Wrong Renderer is shown

### ISSUE THREAD

**Issue by dameiers** [cismet/cids-custom-wuppertal#294]
Steps to reproduce:
1. Stadtbildsearch => search all Stadtilder of year 2010 (ca 490 results)
2. select all search results (strg-a). The creation of the aggregation renderer takes some time.
3. select single object or a subset of the search results
4. after some time it CAN happen that the aggregationrenderer of the strg-a operation appears

![bildschirmfoto vom 2014-11-19 16 19 57](https://cloud.githubusercontent.com/assets/1785245/5108216/93501a4e-7008-11e4-92b4-5e84437f7816.png)

The picture shows that the aggregation renderer and the selections status of the search results dont correspond

**Comment by helllth** [comment]
Couldn't reproduce
